/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class HectorASM */

#ifndef _Included_HectorASM
#define _Included_HectorASM
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     HectorASM
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_HectorASM_add
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     HectorASM
 * Method:    sub
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_HectorASM_sub
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     HectorASM
 * Method:    mul
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_HectorASM_mul
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     HectorASM
 * Method:    div
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_HectorASM_div
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     HectorASM
 * Method:    inc
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_HectorASM_inc
  (JNIEnv *, jobject, jint);

/*
 * Class:     HectorASM
 * Method:    dec
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_HectorASM_dec
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
